// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-llvqhW20DGu7OPAUNAZgS_wjlyjobow',
    appId: '1:337090548271:web:2991e005af938abe466cda',
    messagingSenderId: '337090548271',
    projectId: 'stagi-ec386',
    authDomain: 'stagi-ec386.firebaseapp.com',
    storageBucket: 'stagi-ec386.appspot.com',
    measurementId: 'G-GWWTQETW43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0wXOkE6BVPRsMdZXs8v3tAjPskBlkFwA',
    appId: '1:337090548271:android:da4495a9ed8d8603466cda',
    messagingSenderId: '337090548271',
    projectId: 'stagi-ec386',
    storageBucket: 'stagi-ec386.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrq9B2QLdDgCqsRQJFxBzMC1Lp0y2Nnyw',
    appId: '1:337090548271:ios:37daab23887be135466cda',
    messagingSenderId: '337090548271',
    projectId: 'stagi-ec386',
    storageBucket: 'stagi-ec386.appspot.com',
    androidClientId: '337090548271-r2okr2i0shs9jrf8n5i5hdk65vll9ita.apps.googleusercontent.com',
    iosClientId: '337090548271-uidd9ghmnjhnpmr11i2bnupqflbkdq1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendAppStagi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrq9B2QLdDgCqsRQJFxBzMC1Lp0y2Nnyw',
    appId: '1:337090548271:ios:37daab23887be135466cda',
    messagingSenderId: '337090548271',
    projectId: 'stagi-ec386',
    storageBucket: 'stagi-ec386.appspot.com',
    androidClientId: '337090548271-r2okr2i0shs9jrf8n5i5hdk65vll9ita.apps.googleusercontent.com',
    iosClientId: '337090548271-uidd9ghmnjhnpmr11i2bnupqflbkdq1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendAppStagi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-llvqhW20DGu7OPAUNAZgS_wjlyjobow',
    appId: '1:337090548271:web:eeb6320b346e7e61466cda',
    messagingSenderId: '337090548271',
    projectId: 'stagi-ec386',
    authDomain: 'stagi-ec386.firebaseapp.com',
    storageBucket: 'stagi-ec386.appspot.com',
    measurementId: 'G-LQJLTJDTXL',
  );
}
